% launch several tests

name_list = {   ...
    'sapin', ...
};
%    'chicken',...    
%    'pacman',...
%    'disk-hole', ...
% 'ellipse-fat',...
%    
%    'camel',...
%    'apple',...
%    'square-tube-2', ...

%  
normlist = {'l2' 'l1' 'linf' };

for it=1:length(name_list)
    for itnorm=1:length(normlist)
        options.tv_norm = normlist{itnorm};
        name = name_list{it};
        disp(['----> Processing ' name ', norm ' options.tv_norm '.']);
        test_cheeger_multires;
    end
end